title: GraphStateMachines
description: A Kotlin library for creating state machines using directed graphs
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: kotlin
    css_class: highlight
    guess_lang: true

exclude:
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
